### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable in Batch Normalization Layer

### ISSUE THREAD

**Issue by 2niuhe** [BobMcDear/attorch#6]
I'm encountering a `TypeError` when running the `imagenette` example with the following command:

```bash
python -m examples.imagenette.main --epochs 3
```

#### Error Message
The following error occurs:

```
/content/attorch# python -m examples.imagenette.main --epochs 3
attorch run:
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:617: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/attorch/examples/imagenette/main.py", line 222, in <module>
    main(partial(model_cls, use_attorch=True),
  File "/content/attorch/examples/imagenette/main.py", line 168, in main
    loss = model(input, target)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/attorch/examples/imagenette/resnet.py", line 181, in forward
    output = self.stage1(output)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/attorch/examples/imagenette/resnet.py", line 108, in forward
    output = self.conv_bn_relu3(output, self.downsample(input))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/attorch/examples/imagenette/resnet.py", line 61, in forward
    output = self.bn(output, pre_act_add)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/attorch/attorch/batch_norm_layer.py", line 344, in forward
    return BatchNormAutoGrad.apply(input, self.training,
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 465, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/content/attorch/attorch/batch_norm_layer.py", line 93, in forward
    if '_' in act_func:
TypeError: argument of type 'NoneType' is not iterable

```

#### Steps to Reproduce
1. Clone the repository.
2. Navigate to the `attorch` directory.
3. Run the command mentioned above.

#### Additional Information
- Python version: 3.10
- PyTorch version: 2.5.0+cu121
- Triton version: 3.1
- Environment: google colab T4

#### Possible Cause
It seems that the `act_func` variable in the `BatchNormAutoGrad` class is `None`, leading to a `TypeError` when attempting to check if `'_'` is in it.

**Comment by BobMcDear** [comment]
Thank you for bringing this issue to my attention. It also affects the linear module and has been fixed now.
